### ISSUE TITLE
Unable to install package pyamdgpuinfo on docker container

### ISSUE THREAD

**Issue by setterlee** [DeadEnded/ha-pyamdgpuinfo#2]
Hi, I just added this repo to my HA instance and when I tried to add the integration after the install from HACS, the integration failed. 

The HA logs show this:

```
Unable to install package pyamdgpuinfo: × Failed to download and build `pyamdgpuinfo==2.1.6` ╰─▶ Build backend failed to build wheel through `build_wheel` (exit status: 1) [stdout] running bdist_wheel running build running build_py creating build/lib.linux-x86_64-cpython-313/pyamdgpuinfo copying pyamdgpuinfo/__init__.py -> build/lib.linux-x86_64-cpython-313/pyamdgpuinfo running build_ext building 'pyamdgpuinfo._pyamdgpuinfo' extension creating build/temp.linux-x86_64-cpython-313/pyamdgpuinfo gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fno-semantic-interposition -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/include/libdrm -I/tmp/.tmpmpDCLx/builds-v0/.tmpoxCvLI/include -I/usr/local/include/python3.13 -c pyamdgpuinfo/_pyamdgpuinfo.c -o build/temp.linux-x86_64-cpython-313/pyamdgpuinfo/_pyamdgpuinfo.o [stderr] error: command 'gcc' failed: No such file or directory
``` 

Here my docker-compose:

```
version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:2024.12
    volumes:
      - /home/setterlee/docker-volumes/home-assistant/config:/config
      - /home/setterlee/docker-volumes/home-assistant/media:/media
      - /mnt/frigate:/mnt/frigate:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Santiago
    restart: always
    privileged: true
    network_mode: host
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/dri:/dev/dri
  whisper:
    container_name: whisper
    image: rhasspy/wyoming-whisper
    command: --model base-int8 --language es
    volumes:
      - /home/setterlee/docker-volumes/whisper-data:/data
    environment:
      - TZ=America/Santiago
    restart: always
    network_mode: host
  piper:
    container_name: piper
    image: rhasspy/wyoming-piper
    command: --voice es-mls_9972-low
    volumes:
      - /home/setterlee/docker-volumes/piper-data:/data
    environment:
      - TZ=America/Santiago
    restart: always
    network_mode: host
``` 

Checking the error, the library is traying to complie some dependencies but the home assistant docker image have not installed the "gcc" command. 

I wish to know if you tested the integration with a custom docker image. 

Thanks
